rsvp_umbrella/apps/rsvp_web/web/router.ex
defmodule RsvpWeb.Router do
  use RsvpWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

#  pipeline :authorised do
#    plug :browser
#    plug RsvpWeb.AutorisedPlug
#  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    # in case of using :authorised pipeline remove events routes from here
    get  "/events",    EventController, :list
    get  "/events/new", EventController, :create
    post "/events/new", EventController, :add
    get  "/events/:id", EventController, :show
    post "/events/:id/reserve", EventController, :reserve

    get  "/login", LoginController, :index
    post "/login", LoginController, :login
  end

#  scope "/events", RsvpWeb do
#    pipe_through :authorised
#
#    get  "/",    EventController, :list
#    get  "/new", EventController, :create
#    post "/new", EventController, :add
#    get  "/:id", EventController, :show
#  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWeb do
  #   pipe_through :api
  # end
end

rsvp_umbrella/apps/rsvp_web/lib/plugs/autorised_plug.ex
defmodule RsvpWeb.AutorisedPlug do
  import Plug.Conn
  import Phoenix.Controller

  def init(opts) do
    opts
  end
  
  def call(conn, name) do
    user_name = conn.cookies["user_name"]

    authorise_user(conn, user_name, name)
  end
  
  defp authorise_user(conn, nil, _) do
    conn
    |> redirect(to: "/login")
    |> halt
  end

  defp authorise_user(conn, user_name, name) when user_name === name do
    conn
  end
  
  defp authorise_user(conn, _, _), do: authorise_user(conn, nil, nil)
end

rsvp_umbrella/apps/rsvp_web/web/controllers/event_controller.ex
defmodule RsvpWeb.EventController do
    use RsvpWeb.Web, :controller

    plug RsvpWeb.AutorisedPlug, "create" when action in [:create]
    
    def show(conn, %{"id" => id}) do
        event = Rsvp.EventQueries.get_by_id(id)
        render conn, "details.html", event: event
    end

    def list(conn, _params) do
        events = Rsvp.EventQueries.get_all()
        render conn, "list.html", events: events
    end
    
    def create(conn, %{errors: errors}) do
        render conn, "create.html", changeset: errors
    end
    
    def create(conn, _params) do
        changeset = Rsvp.Events.changeset(%Rsvp.Events{}, %{})
        render conn, "create.html", changeset: changeset
    end
    
    def add(conn, %{"events" => events}) do
        events = Map.update!(events, "date", fn d -> d <> ":00" end)

        changeset = Rsvp.Events.changeset(%Rsvp.Events{}, events)

        case Rsvp.EventQueries.create changeset do
          {:ok, %{id: id}} -> redirect conn, to: event_path(conn, :show, id)
          {:error, reasons} -> create conn, %{errors: reasons}
        end
    end
    
    def reserve(conn, %{"id" => id, "reservation" => %{"quantity" => quantity}}) do
      {:ok, event} = Rsvp.EventQueries.decrease_quantity(id, quantity)
      RsvpWeb.EventChannel.send_update(event)
      redirect conn, to: event_path(conn, :show, id)
    end
end

rsvp_umbrella/apps/rsvp_web/web/controllers/login_controller.ex
defmodule RsvpWeb.LoginController do
  use RsvpWeb.Web, :controller

  def index(conn, _) do
    render conn, "login.html"
  end

  def login(conn, %{"login" => %{"username" => name}}) do
    expiration = 60*60*24*7
    conn
    |> Plug.Conn.put_resp_cookie("user_name", name, max_age: expiration)
    |> redirect(to: "/")
  end
end

rsvp_umbrella/apps/rsvp_web/web/controllers/page_controller.ex
defmodule RsvpWeb.PageController do
  use RsvpWeb.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

rsvp_umbrella/apps/rsvp_web/web/views/error_view.ex
defmodule RsvpWeb.ErrorView do
  use RsvpWeb.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

rsvp_umbrella/apps/rsvp_web/web/views/event_view.ex
defmodule RsvpWeb.EventView do
    use RsvpWeb.Web, :view

    def format_date(date) do
        {{y, m, d}, _} = Ecto.DateTime.to_erl(date)
        "#{pad_leading(d)}/#{pad_leading(m)}/#{y}"
    end

    def format_time(date) do
      {_, {h, m, s}} = Ecto.DateTime.to_erl(date)
      "#{pad_leading(h)}:#{pad_leading(m)}:#{pad_leading(s)}"
    end

    defp pad_leading(num) do
        num
        |> Integer.to_string
        |> String.pad_leading(2, "0")
    end
end

rsvp_umbrella/apps/rsvp_web/web/views/layout_view.ex
defmodule RsvpWeb.LayoutView do
  use RsvpWeb.Web, :view
end

rsvp_umbrella/apps/rsvp_web/web/views/login_view.ex
defmodule RsvpWeb.LoginView do
  use RsvpWeb.Web, :view
end

rsvp_umbrella/apps/rsvp_web/web/views/page_view.ex
defmodule RsvpWeb.PageView do
  use RsvpWeb.Web, :view
end

rsvp_umbrella/apps/rsvp_web/web/views/shared_view.ex
defmodule RsvpWeb.SharedView do
    use RsvpWeb.Web, :view
end

rsvp_umbrella/apps/rsvp_web/web/templates/event/create.html.eex
<h1>Add Event</h1>
<%= form_for @changeset, event_path(@conn, :add), fn f -> %>
    <div class="form-group">
        <%= label f, :title, "Title" %>
        <%= text_input f, :title, class: "form-control" %>
        <%= error_tag f, :title %>
    </div>

    <div class="form-group">
        <%= label f, :location, "Location" %>
        <%= text_input f, :location, class: "form-control" %>
        <%= error_tag f, :location %>
    </div>

    <div class="form-group">
        <%= label f, :date, "Date & Time" %>
        <%= text_input f, :date, class: "form-control", type: "datetime-local" %>
        <%= error_tag f, :date %>
    </div>

    <div class="form-group">
        <%= label f, :description, "Description" %>
        <%= textarea f, :description, class: "form-control", rows: 5 %>
    </div>

    <%= submit "Add", class: "btn btn-primary pull-right" %>
<% end %>

rsvp_umbrella/apps/rsvp_web/web/templates/event/details.html.eex
<h1><%= @event.title %> <small><%= @event.location %></small></h1>
<h3><%= format_date @event.date %> <small>at <%= format_time @event.date %></small></h3>
<p><%= @event.description %></p>
<h4>Available Spots: <span class="quantity"><%= @event.quantity_available %></span></h4>

<%= form_for @conn, event_path(@conn, :reserve, @event.id), [as: :reservation, class: "form-inline"], fn f -> %>
    <div class="form-group">
        <%= label f, :quantity, "Quantity" %>
        <%= number_input f, :quantity, class: "form-control", min: 1 %>
    </div>

    <%= submit "Reserve", class: "btn btn-primary pull-right" %>
<% end %>

<span id="id" data-id="<%= @event.id %>"></span>

rsvp_umbrella/apps/rsvp_web/web/templates/event/list.html.eex
<h1>All Events</h1>
<a href="<%= event_path(@conn, :create) %>" class="btn btn-primary pull-right">Add Event</a>
<%= render RsvpWeb.SharedView, "count.html", list: @events %>
<div class="list-group">
    <%= for e <- @events do %>
        <%= render "summary.html", event: e, conn: @conn %>
    <% end %>
</div>

rsvp_umbrella/apps/rsvp_web/web/templates/event/summary.html.eex
<a href="<%= event_path(@conn, :show, @event.id) %>">
    <div class="list-group-item">
        <h4 class="list-group-item-heading"><%= @event.title %></h4>
        <span>
            <span class="text-muted"><%= @event.location %></span>
            <span class="pull-right">
                <strong><%= format_date @event.date %></strong>
            </span>
        </span>
    </div>
</a>

rsvp_umbrella/apps/rsvp_web/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>RSVP</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <ul class="nav nav-pills col-xs-offset-7">
        <li><a href="/">Home</a></li>
        <li><a href="<%= event_path(@conn, :list) %>">Events</a></li>
        <li><a href="<%= login_path(@conn, :index) %>">Login</a></li>
    </ul>

    <div class="container">
      <header class="header">
          <span class="title">RSPV</span>
          <span class="sub-title">Your online directory of events</span>
          <%= if @conn.cookies["user_name"] do %>
            <span>
                Hello, <%= @conn.cookies["user_name"] %>
            </span>
          <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

rsvp_umbrella/apps/rsvp_web/web/templates/login/login.html.eex
<%= form_for @conn, login_path(@conn, :login), [as: :login], fn f -> %>
    <%= text_input f, :username %>
    <%= submit "Login" %>
<% end %>

rsvp_umbrella/apps/rsvp_web/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "RSVP!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

rsvp_umbrella/apps/rsvp_web/web/templates/shared/count.html.eex
<h3>Total Count: <%= Enum.count @list %></h3>